const USERS_TABLE = process.env.DB_USERS_TABLE || 'usuarios';
const PROVIDERS_TABLE = process.env.DB_PROVIDERS_TABLE || 'proveedores';
const CLIENTS_TABLE = process.env.DB_CLIENTS_TABLE || 'clientes';
const ENTRIES_TABLE = process.env.DB_ENTRIES_TABLE || 'entradas_mercancia';
const ENTRADA_UNIDADES_TABLE = process.env.DB_ENTRADA_UNIDADES_TABLE || 'entrada_unidades';
const INVENTORY_TABLE = process.env.DB_INVENTORY_TABLE || 'inventario_existencias';
const MOVEMENTS_TABLE = process.env.DB_MOVEMENTS_TABLE || 'movimientos_inventario';
const PRODUCTS_TABLE = process.env.DB_PRODUCTS_TABLE || 'productos';
const SERVICE_TYPES_TABLE = process.env.DB_SERVICE_TYPES_TABLE || 'tipos_servicio';
const RAW_MATERIAL_LOTS_TABLE = process.env.DB_RAW_MATERIAL_LOTS_TABLE || 'lotes_materia_prima';
const MATURATION_SUBLOT_TABLE = process.env.DB_MATURATION_SUBLOT_TABLE || 'sublotes_maduracion';
const MATURATION_CONTROL_TABLE = process.env.DB_MATURATION_CONTROL_TABLE || 'control_maduracion';
const GREEN_NET_TABLE = process.env.DB_GREEN_NET_TABLE || 'redes_verde_detalle';
const CAT_MERMA_TABLE = process.env.DB_CAT_MERMA_TABLE || 'cat_tipos_merma';
const CAT_STAGE_TABLE = process.env.DB_CAT_STAGE_TABLE || 'cat_tipos_etapa';
const PRODUCTION_ORDERS_TABLE = process.env.DB_PRODUCTION_ORDERS_TABLE || 'ordenes_produccion';
const PRODUCTION_TABLE = process.env.DB_PRODUCTION_TABLE || 'procesos_produccion';
const PRODUCTION_STAGE_TABLE = process.env.DB_PRODUCTION_STAGE_TABLE || 'produccion_etapas';
const PRODUCTION_MERMA_TABLE = process.env.DB_PRODUCTION_MERMA_TABLE || 'produccion_mermas';
const PRODUCTION_INSUMO_TABLE = process.env.DB_PRODUCTION_INSUMO_TABLE || 'produccion_insumos';
const PRODUCTION_COLD_ROOM_TABLE =
  process.env.DB_PRODUCTION_COLD_ROOM_TABLE || 'produccion_cuartos_frio';
const VEHICLES_TABLE = process.env.DB_VEHICLES_TABLE || 'vehiculos';
const VEHICLE_SERVICES_TABLE = process.env.DB_VEHICLE_SERVICES_TABLE || 'servicios_vehiculo';
const VEHICLE_MILEAGE_REPORTS_TABLE =
  process.env.DB_VEHICLE_MILEAGE_REPORTS_TABLE || 'reporte_kilometraje_vehiculo';
const ORDERS_TABLE = process.env.DB_ORDERS_TABLE || 'pedidos';
const ORDER_DETAIL_TABLE = process.env.DB_ORDER_DETAIL_TABLE || 'pedido_detalle';
const ROUTES_TABLE = process.env.DB_ROUTES_TABLE || 'rutas_entrega';
const ROUTE_ORDERS_TABLE = process.env.DB_ROUTE_ORDERS_TABLE || 'ruta_pedidos';
const ORDER_RETURNS_TABLE = process.env.DB_ORDER_RETURNS_TABLE || 'devoluciones_pedido';
const ACTIVE_STATE = 'Activo';
const INACTIVE_STATE = 'Inactivo';
const PENDING_STATE = 'Pendiente';
const COMPLETE_STATE = 'Completo';
const PRODUCTION_ACTIVE_STATE = 'En proceso';
const PRODUCTION_FINISHED_STATE = 'Finalizado';
const RAW_MATERIAL_PRODUCT_TYPE = 'Materia Prima';
const SUBLOT_ACTIVE_STATE = 'Activo';
const SUBLOT_READY_STATE = 'Listo para produccion';
const SUBLOT_SENT_STATE = 'Enviado a produccion';
const SUBLOT_GREEN_NET_STATE = 'Derivado a red';
const MATURE_RIPENESS_STATE = 'Maduro';
const MATURATION_BRIX_THRESHOLD = Number(process.env.MATURATION_BRIX_THRESHOLD) || 22;
const BALANCE_TOLERANCE_KG = 0.01;
const FINISHED_PRODUCT_TYPE = 'Producto Terminado';
const PILOT_ROLE = 'Piloto';
const VEHICLE_AVAILABLE_STATE = 'Disponible';
const VEHICLE_EN_ROUTE_STATE = 'En Ruta';
const ORDER_PREPARADO_STATE = 'Preparado';
const ORDER_EN_RUTA_STATE = 'En Ruta';
const ORDER_ENTREGADO_STATE = 'Entregado';
const ORDER_CON_DEVOLUCION_STATE = 'Con Devolucion';
const ORDER_CANCELADO_STATE = 'Cancelado';
const ORDER_DETAIL_ENTREGADO_STATE = 'Entregado';
const ORDER_DETAIL_PARCIAL_STATE = 'Parcial';
const ORDER_DETAIL_RECHAZADO_STATE = 'Rechazado';
const ORDER_DETAIL_DEVUELTO_STATE = 'Devuelto';
const ROUTE_PREPARADO_STATE = 'Preparado';
const ROUTE_EN_RUTA_STATE = 'En Ruta';
const ROUTE_CERRADA_STATE = 'Cerrada';
const RETURN_PENDING_REVIEW_STATE = 'Pendiente de revision';
const RETURN_REINGRESADO_STATE = 'Reingresado a inventario';
const RETURN_PERDIDA_STATE = 'Perdida';
const ADMIN_ROLE = 'Administrador';
const PRODUCTION_ORDER_PENDIENTE_STATE = 'Pendiente';
const PRODUCTION_ORDER_EN_PROCESO_STATE = 'En Proceso';
const PRODUCTION_ORDER_COMPLETADA_STATE = 'Completada';
const PRODUCTION_ORDER_CANCELADA_STATE = 'Cancelada';

module.exports = {
  USERS_TABLE,
  PROVIDERS_TABLE,
  CLIENTS_TABLE,
  ENTRIES_TABLE,
  ENTRADA_UNIDADES_TABLE,
  INVENTORY_TABLE,
  MOVEMENTS_TABLE,
  PRODUCTS_TABLE,
  SERVICE_TYPES_TABLE,
  RAW_MATERIAL_LOTS_TABLE,
  MATURATION_SUBLOT_TABLE,
  MATURATION_CONTROL_TABLE,
  GREEN_NET_TABLE,
  CAT_MERMA_TABLE,
  CAT_STAGE_TABLE,
  PRODUCTION_ORDERS_TABLE,
  PRODUCTION_TABLE,
  PRODUCTION_STAGE_TABLE,
  PRODUCTION_MERMA_TABLE,
  PRODUCTION_INSUMO_TABLE,
  PRODUCTION_COLD_ROOM_TABLE,
  VEHICLES_TABLE,
  VEHICLE_SERVICES_TABLE,
  VEHICLE_MILEAGE_REPORTS_TABLE,
  ORDERS_TABLE,
  ORDER_DETAIL_TABLE,
  ROUTES_TABLE,
  ROUTE_ORDERS_TABLE,
  ORDER_RETURNS_TABLE,
  ACTIVE_STATE,
  INACTIVE_STATE,
  PENDING_STATE,
  COMPLETE_STATE,
  PRODUCTION_ACTIVE_STATE,
  PRODUCTION_FINISHED_STATE,
  RAW_MATERIAL_PRODUCT_TYPE,
  SUBLOT_ACTIVE_STATE,
  SUBLOT_READY_STATE,
  SUBLOT_SENT_STATE,
  SUBLOT_GREEN_NET_STATE,
  MATURE_RIPENESS_STATE,
  MATURATION_BRIX_THRESHOLD,
  BALANCE_TOLERANCE_KG,
  FINISHED_PRODUCT_TYPE,
  PILOT_ROLE,
  VEHICLE_AVAILABLE_STATE,
  VEHICLE_EN_ROUTE_STATE,
  ORDER_PREPARADO_STATE,
  ORDER_EN_RUTA_STATE,
  ORDER_ENTREGADO_STATE,
  ORDER_CON_DEVOLUCION_STATE,
  ORDER_CANCELADO_STATE,
  ORDER_DETAIL_ENTREGADO_STATE,
  ORDER_DETAIL_PARCIAL_STATE,
  ORDER_DETAIL_RECHAZADO_STATE,
  ORDER_DETAIL_DEVUELTO_STATE,
  ROUTE_PREPARADO_STATE,
  ROUTE_EN_RUTA_STATE,
  ROUTE_CERRADA_STATE,
  RETURN_PENDING_REVIEW_STATE,
  RETURN_REINGRESADO_STATE,
  RETURN_PERDIDA_STATE,
  ADMIN_ROLE,
  PRODUCTION_ORDER_PENDIENTE_STATE,
  PRODUCTION_ORDER_EN_PROCESO_STATE,
  PRODUCTION_ORDER_COMPLETADA_STATE,
  PRODUCTION_ORDER_CANCELADA_STATE,
};
